version: '3.8'

services:
  mongo:
    image: mongo
    container_name: slot_mongo
    build:
      context: .
      dockerfile: mongo.dockerfile
    ports:
      - "6060:27017"
    env_file:
      - .env.prod
    networks:
      - slot_network

networks:
  slot_network:
    driver: bridge
